### ISSUE TITLE
如果URL中有&字符的话不太行

### ISSUE THREAD

**Issue by Crumbled-potato** [ByteTu/Api-N_m3u8DL#1]
命令行直接会把&当成运算符。
建议优化一下。

**Comment by ByteTu** [comment]
请求json内容发一下我看看

**Comment by Crumbled-potato** [comment]
我的url信息有些敏感，所以脱敏了一下。url虽然是无效，但是如果用这个url测试的话，log日志可以看到&后边的e=1699911466都没有被识别

args = {
                   "app": "re",
                   "must":  https://internal-video.xxxxxxxx.com/1/11568/106/1921/xxxxx-xxxxxx-at-xxxxxx-xxxxxx-32KJQV4/master.m3u8?st=GwDJObQr0MVn_aOqJ4aaacCE&e=1699911466,
                   "--save-name": name,
                   "--save-dir": "../Downloads",
                   "--del-after-done": "True",
                   "--auto-select": "True"
             }

**Comment by ByteTu** [comment]
已修复此问题请下载最新发行版进行测试。如有问题请提供base64加密的完整url地址

**Comment by Crumbled-potato** [comment]
经测试发现，如果url和文件名都有e的话，文件名会不完整。
例如
args = {
"app": "re",
"must": https://internal-video.xxxxxxxx.com/1/11568/106/1921/xxxxx-xxxxxx-at-xxxxxx-xxxxxx-32KJQV4/master.m3u8?st=GwDJObQr0MVn_aOqJ4aaacCE&e=1699911466,
"--save-name": “Adam&Edavn”,
"--save-dir": "../Downloads",
"--del-after-done": "True",
"--auto-select": "True"
}

日志中：
保存文件名: Adam_
